### ISSUE TITLE
cannot import name 'get_jac_normals_torch'

### ISSUE THREAD

**Issue by bguillard** [rahulvenkk/csp-net#1]
Hi, and thank you for your great work!
When testing a model trained on the lion shape, I run into the following issue:
```
ImportError: cannot import name 'get_jac_normals_torch'
```

and indeed the said function is missing from ```single_shape_csp/pt_pred/train_utils.py```. Could you please provide it? Thanks a lot in advance.

----------------------------------------------------------------------
Unrelated: I think saving the network's weights during training has a typo in ```single_shape_csp/pt_pred/train.py``` on line 162:
https://github.com/rahulvenkk/csp-net/blob/58915f9ab280495d2078f32789b10fe2b77ebef7/single_shape_csp/pt_pred/train.py#L162
and should rather read
```python
torch.save(net.state_dict(), config.weights_path + '/' + str(total_iters) + '.pth') 
```
(```total_iters``` instead of ```it```)

Best,
Benoit

**Comment by tejank10** [comment]
Hi Benoit,

Thanks a lot for your interest in our work and for pointing out the bug. I have added that function now.
