### ISSUE TITLE
cannot find the directory "surface_recon/im2mesh/data"

### ISSUE THREAD

**Issue by dnvtmf** [rahulvenkk/csp-net#2]
Thank you for your work. When I want to train a model using surface_recon, I found it cannot done due to the lack of source. I wish you can complete your code.

Besides, are there pretrained models to download?

Best

**Comment by tejank10** [comment]
Hi Diwen, thanks for your interest in our work!

[Here](https://huggingface.co/tejank10/cspnet/resolve/main/model_best.pt) is the link to the pretrained model.

Could you please elaborate on the difficulty that you are facing in the training the model? 

Thanks.

**Comment by dnvtmf** [comment]
Thanks for your reply. 

In short, there should be a folder **data** in the directory **surface_recon/im2mesh**, just like Occupancy  Networks. 

However, I can not find it.

**Comment by tejank10** [comment]
Thanks for pointing out, the code has been updated.
